// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Contact documents */
interface ContactDocumentData {
    /**
     * Phone Number field in *Contact*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.phone_number
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phone_number: prismicT.KeyTextField;
    /**
     * Postal Address field in *Contact*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.postal_address
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    postal_address: prismicT.KeyTextField;
    /**
     * Email field in *Contact*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.email
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    email: prismicT.KeyTextField;
    /**
     * Instagram Link field in *Contact*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.instagram_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    instagram_link: prismicT.LinkField;
    /**
     * Facebook Link field in *Contact*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.facebook_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    facebook_link: prismicT.LinkField;
    /**
     * Youtube Link field in *Contact*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.youtube_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    youtube_link: prismicT.LinkField;
    /**
     * WhatsApp Link field in *Contact*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.whatsapp_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    whatsapp_link: prismicT.LinkField;
    /**
     * GoogleMaps Link field in *Contact*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.googlemaps_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    googlemaps_link: prismicT.LinkField;
    /**
     * Slice Zone field in *Contact*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ContactDocumentDataSlicesSlice>;
}
/**
 * Slice for *Contact → Slice Zone*
 *
 */
type ContactDocumentDataSlicesSlice = never;
/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ContactDocumentData>, "contact", Lang>;
/** Content for Home Page documents */
interface HomePageDocumentData {
    /**
     * Meta Title field in *Home Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.meta_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismicT.KeyTextField;
    /**
     * Meta Description field in *Home Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.meta_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_description: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Home Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomePageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Home Page → Slice Zone*
 *
 */
type HomePageDocumentDataSlicesSlice = HeroSlice | InfiniteImagesSliderSlice | UnstructuredTextImagesSlice | IconsTextsListSlice | SpacedUnstructuredTextImagesSlice | TextImagesSliderSlice | CustomerReviewsSlice | ButtonLinksSlice;
/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomePageDocumentData>, "home_page", Lang>;
/** Content for Navigation documents */
interface NavigationDocumentData {
    /**
     * Entries field in *Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.entries[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    entries: prismicT.GroupField<Simplify<NavigationDocumentDataEntriesItem>>;
    /**
     * Slice Zone field in *Navigation*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<NavigationDocumentDataSlicesSlice>;
}
/**
 * Item in Navigation → Entries
 *
 */
export interface NavigationDocumentDataEntriesItem {
    /**
     * Entry Name field in *Navigation → Entries*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.entries[].entry_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    entry_name: prismicT.KeyTextField;
    /**
     * Entry Target field in *Navigation → Entries*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.entries[].entry_target
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    entry_target: prismicT.KeyTextField;
    /**
     * Button Look field in *Navigation → Entries*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: navigation.entries[].button_look
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    button_look: prismicT.BooleanField;
}
/**
 * Slice for *Navigation → Slice Zone*
 *
 */
type NavigationDocumentDataSlicesSlice = never;
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, "navigation", Lang>;
export type AllDocumentTypes = ContactDocument | HomePageDocument | NavigationDocument;
/**
 * Primary content in ButtonLinks → Primary
 *
 */
interface ButtonLinksSliceDefaultPrimary {
    /**
     * Section ID field in *ButtonLinks → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: button_links.primary.section_id
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    section_id: prismicT.KeyTextField;
    /**
     * Title field in *ButtonLinks → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: button_links.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in ButtonLinks → Items
 *
 */
export interface ButtonLinksSliceDefaultItem {
    /**
     * Link field in *ButtonLinks → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: button_links.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * icon field in *ButtonLinks → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: button_links.items[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    icon: prismicT.ImageField<never>;
    /**
     * Color field in *ButtonLinks → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Closest matches the brand's colour
     * - **API ID Path**: button_links.items[].color
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    color: prismicT.SelectField<"Blue" | "Red" | "Green" | "Yellow">;
}
/**
 * Default variation for ButtonLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ButtonLinks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ButtonLinksSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ButtonLinksSliceDefaultPrimary>, Simplify<ButtonLinksSliceDefaultItem>>;
/**
 * Slice variation for *ButtonLinks*
 *
 */
type ButtonLinksSliceVariation = ButtonLinksSliceDefault;
/**
 * ButtonLinks Shared Slice
 *
 * - **API ID**: `button_links`
 * - **Description**: `ButtonLinks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ButtonLinksSlice = prismicT.SharedSlice<"button_links", ButtonLinksSliceVariation>;
/**
 * Primary content in CustomerReviews → Primary
 *
 */
interface CustomerReviewsSliceDefaultPrimary {
    /**
     * Section ID field in *CustomerReviews → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: customer_reviews.primary.section_id
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    section_id: prismicT.KeyTextField;
    /**
     * Title field in *CustomerReviews → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: customer_reviews.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in CustomerReviews → Items
 *
 */
export interface CustomerReviewsSliceDefaultItem {
    /**
     * Review Link field in *CustomerReviews → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: customer_reviews.items[].review_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    review_link: prismicT.LinkField;
    /**
     * Platform Name field in *CustomerReviews → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: customer_reviews.items[].platform_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    platform_name: prismicT.KeyTextField;
    /**
     * Customer Name field in *CustomerReviews → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: customer_reviews.items[].customer_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    customer_name: prismicT.KeyTextField;
    /**
     * Customer Image field in *CustomerReviews → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: customer_reviews.items[].customer_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    customer_image: prismicT.ImageField<never>;
    /**
     * Stars field in *CustomerReviews → Items*
     *
     * - **Field Type**: Number
     * - **Placeholder**: max 5
     * - **API ID Path**: customer_reviews.items[].stars
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    stars: prismicT.NumberField;
    /**
     * Review Text field in *CustomerReviews → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: customer_reviews.items[].review_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    review_text: prismicT.KeyTextField;
}
/**
 * Default variation for CustomerReviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: `CustomerReviews`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CustomerReviewsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CustomerReviewsSliceDefaultPrimary>, Simplify<CustomerReviewsSliceDefaultItem>>;
/**
 * Slice variation for *CustomerReviews*
 *
 */
type CustomerReviewsSliceVariation = CustomerReviewsSliceDefault;
/**
 * CustomerReviews Shared Slice
 *
 * - **API ID**: `customer_reviews`
 * - **Description**: `CustomerReviews`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CustomerReviewsSlice = prismicT.SharedSlice<"customer_reviews", CustomerReviewsSliceVariation>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
    /**
     * Section ID field in *Hero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.section_id
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    section_id: prismicT.KeyTextField;
    /**
     * Title field in *Hero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Subtitle field in *Hero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    subtitle: prismicT.KeyTextField;
    /**
     * Image field in *Hero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Primary content in IconsTextsList → Primary
 *
 */
interface IconsTextsListSliceDefaultPrimary {
    /**
     * Section ID field in *IconsTextsList → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: icons_texts_list.primary.section_id
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    section_id: prismicT.KeyTextField;
    /**
     * Title field in *IconsTextsList → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: icons_texts_list.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *IconsTextsList → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: icons_texts_list.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Item in IconsTextsList → Items
 *
 */
export interface IconsTextsListSliceDefaultItem {
    /**
     * Text field in *IconsTextsList → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: icons_texts_list.items[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    text: prismicT.KeyTextField;
    /**
     * Icon field in *IconsTextsList → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: icons_texts_list.items[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    icon: prismicT.ImageField<never>;
}
/**
 * Default variation for IconsTextsList Slice
 *
 * - **API ID**: `default`
 * - **Description**: `IconsTextsList`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IconsTextsListSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<IconsTextsListSliceDefaultPrimary>, Simplify<IconsTextsListSliceDefaultItem>>;
/**
 * Slice variation for *IconsTextsList*
 *
 */
type IconsTextsListSliceVariation = IconsTextsListSliceDefault;
/**
 * IconsTextsList Shared Slice
 *
 * - **API ID**: `icons_texts_list`
 * - **Description**: `IconsTextsList`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IconsTextsListSlice = prismicT.SharedSlice<"icons_texts_list", IconsTextsListSliceVariation>;
/**
 * Primary content in InfiniteImagesSlider → Primary
 *
 */
interface InfiniteImagesSliderSliceDefaultPrimary {
    /**
     * Section ID field in *InfiniteImagesSlider → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: infinite_images_slider.primary.section_id
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    section_id: prismicT.KeyTextField;
    /**
     * Auto field in *InfiniteImagesSlider → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: infinite_images_slider.primary.auto
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    auto: prismicT.BooleanField;
}
/**
 * Item in InfiniteImagesSlider → Items
 *
 */
export interface InfiniteImagesSliderSliceDefaultItem {
    /**
     * Image field in *InfiniteImagesSlider → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: infinite_images_slider.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for InfiniteImagesSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: `InfiniteImagesSlider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfiniteImagesSliderSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<InfiniteImagesSliderSliceDefaultPrimary>, Simplify<InfiniteImagesSliderSliceDefaultItem>>;
/**
 * Slice variation for *InfiniteImagesSlider*
 *
 */
type InfiniteImagesSliderSliceVariation = InfiniteImagesSliderSliceDefault;
/**
 * InfiniteImagesSlider Shared Slice
 *
 * - **API ID**: `infinite_images_slider`
 * - **Description**: `InfiniteImagesSlider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfiniteImagesSliderSlice = prismicT.SharedSlice<"infinite_images_slider", InfiniteImagesSliderSliceVariation>;
/**
 * Primary content in SpacedUnstructuredTextImages → Primary
 *
 */
interface SpacedUnstructuredTextImagesSliceDefaultPrimary {
    /**
     * Section ID field in *SpacedUnstructuredTextImages → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: spaced_unstructured_text_images.primary.section_id
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    section_id: prismicT.KeyTextField;
    /**
     * Title field in *SpacedUnstructuredTextImages → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: spaced_unstructured_text_images.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *SpacedUnstructuredTextImages → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: spaced_unstructured_text_images.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * TopRightImage field in *SpacedUnstructuredTextImages → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: spaced_unstructured_text_images.primary.toprightimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    toprightimage: prismicT.ImageField<never>;
    /**
     * LeftImage field in *SpacedUnstructuredTextImages → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: spaced_unstructured_text_images.primary.leftimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    leftimage: prismicT.ImageField<never>;
    /**
     * TextLeftImage field in *SpacedUnstructuredTextImages → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: spaced_unstructured_text_images.primary.textleftimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    textleftimage: prismicT.KeyTextField;
    /**
     * RightImage field in *SpacedUnstructuredTextImages → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: spaced_unstructured_text_images.primary.rightimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    rightimage: prismicT.ImageField<never>;
    /**
     * BottomImage field in *SpacedUnstructuredTextImages → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: spaced_unstructured_text_images.primary.bottomimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    bottomimage: prismicT.ImageField<never>;
    /**
     * TextBottomImage field in *SpacedUnstructuredTextImages → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: spaced_unstructured_text_images.primary.textbottomimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    textbottomimage: prismicT.KeyTextField;
}
/**
 * Default variation for SpacedUnstructuredTextImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SpacedUnstructuredTextImages`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SpacedUnstructuredTextImagesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SpacedUnstructuredTextImagesSliceDefaultPrimary>, never>;
/**
 * Slice variation for *SpacedUnstructuredTextImages*
 *
 */
type SpacedUnstructuredTextImagesSliceVariation = SpacedUnstructuredTextImagesSliceDefault;
/**
 * SpacedUnstructuredTextImages Shared Slice
 *
 * - **API ID**: `spaced_unstructured_text_images`
 * - **Description**: `SpacedUnstructuredTextImages`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SpacedUnstructuredTextImagesSlice = prismicT.SharedSlice<"spaced_unstructured_text_images", SpacedUnstructuredTextImagesSliceVariation>;
/**
 * Primary content in TextImagesSlider → Primary
 *
 */
interface TextImagesSliderSliceDefaultPrimary {
    /**
     * Section ID field in *TextImagesSlider → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_images_slider.primary.section_id
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    section_id: prismicT.KeyTextField;
    /**
     * Title field in *TextImagesSlider → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_images_slider.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *TextImagesSlider → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_images_slider.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Item in TextImagesSlider → Items
 *
 */
export interface TextImagesSliderSliceDefaultItem {
    /**
     * Title field in *TextImagesSlider → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_images_slider.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *TextImagesSlider → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_images_slider.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Image field in *TextImagesSlider → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: text_images_slider.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for TextImagesSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextImagesSlider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextImagesSliderSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextImagesSliderSliceDefaultPrimary>, Simplify<TextImagesSliderSliceDefaultItem>>;
/**
 * Slice variation for *TextImagesSlider*
 *
 */
type TextImagesSliderSliceVariation = TextImagesSliderSliceDefault;
/**
 * TextImagesSlider Shared Slice
 *
 * - **API ID**: `text_images_slider`
 * - **Description**: `TextImagesSlider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextImagesSliderSlice = prismicT.SharedSlice<"text_images_slider", TextImagesSliderSliceVariation>;
/**
 * Primary content in UnstructuredTextImages → Primary
 *
 */
interface UnstructuredTextImagesSliceDefaultPrimary {
    /**
     * Section ID field in *UnstructuredTextImages → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: unstructured_text_images.primary.section_id
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    section_id: prismicT.KeyTextField;
    /**
     * Title field in *UnstructuredTextImages → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: unstructured_text_images.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *UnstructuredTextImages → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: unstructured_text_images.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Link field in *UnstructuredTextImages → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: unstructured_text_images.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * Text Link field in *UnstructuredTextImages → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: unstructured_text_images.primary.text_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    text_link: prismicT.KeyTextField;
    /**
     * TopLeftImage field in *UnstructuredTextImages → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: unstructured_text_images.primary.topleftimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    topleftimage: prismicT.ImageField<never>;
    /**
     * TopRightImage field in *UnstructuredTextImages → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: unstructured_text_images.primary.toprightimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    toprightimage: prismicT.ImageField<never>;
    /**
     * BottomLeftImage field in *UnstructuredTextImages → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: unstructured_text_images.primary.bottomleftimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    bottomleftimage: prismicT.ImageField<never>;
    /**
     * BottomRightImage field in *UnstructuredTextImages → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: unstructured_text_images.primary.bottomrightimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    bottomrightimage: prismicT.ImageField<never>;
    /**
     * Bottom Image field in *UnstructuredTextImages → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: unstructured_text_images.primary.bottom_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    bottom_image: prismicT.ImageField<never>;
    /**
     * Bottom Title field in *UnstructuredTextImages → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: unstructured_text_images.primary.bottom_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    bottom_title: prismicT.KeyTextField;
    /**
     * Bottom Description field in *UnstructuredTextImages → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: unstructured_text_images.primary.bottom_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    bottom_description: prismicT.KeyTextField;
}
/**
 * Default variation for UnstructuredTextImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: `UnstructuredTextImages`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type UnstructuredTextImagesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<UnstructuredTextImagesSliceDefaultPrimary>, never>;
/**
 * Slice variation for *UnstructuredTextImages*
 *
 */
type UnstructuredTextImagesSliceVariation = UnstructuredTextImagesSliceDefault;
/**
 * UnstructuredTextImages Shared Slice
 *
 * - **API ID**: `unstructured_text_images`
 * - **Description**: `UnstructuredTextImages`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type UnstructuredTextImagesSlice = prismicT.SharedSlice<"unstructured_text_images", UnstructuredTextImagesSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ContactDocumentData, ContactDocumentDataSlicesSlice, ContactDocument, HomePageDocumentData, HomePageDocumentDataSlicesSlice, HomePageDocument, NavigationDocumentData, NavigationDocumentDataEntriesItem, NavigationDocumentDataSlicesSlice, NavigationDocument, AllDocumentTypes, ButtonLinksSliceDefaultPrimary, ButtonLinksSliceDefaultItem, ButtonLinksSliceDefault, ButtonLinksSliceVariation, ButtonLinksSlice, CustomerReviewsSliceDefaultPrimary, CustomerReviewsSliceDefaultItem, CustomerReviewsSliceDefault, CustomerReviewsSliceVariation, CustomerReviewsSlice, HeroSliceDefaultPrimary, HeroSliceDefault, HeroSliceVariation, HeroSlice, IconsTextsListSliceDefaultPrimary, IconsTextsListSliceDefaultItem, IconsTextsListSliceDefault, IconsTextsListSliceVariation, IconsTextsListSlice, InfiniteImagesSliderSliceDefaultPrimary, InfiniteImagesSliderSliceDefaultItem, InfiniteImagesSliderSliceDefault, InfiniteImagesSliderSliceVariation, InfiniteImagesSliderSlice, SpacedUnstructuredTextImagesSliceDefaultPrimary, SpacedUnstructuredTextImagesSliceDefault, SpacedUnstructuredTextImagesSliceVariation, SpacedUnstructuredTextImagesSlice, TextImagesSliderSliceDefaultPrimary, TextImagesSliderSliceDefaultItem, TextImagesSliderSliceDefault, TextImagesSliderSliceVariation, TextImagesSliderSlice, UnstructuredTextImagesSliceDefaultPrimary, UnstructuredTextImagesSliceDefault, UnstructuredTextImagesSliceVariation, UnstructuredTextImagesSlice };
    }
}
