// Code generated by Slice Machine. DO NOT EDIT.

import ButtonLinks from './ButtonLinks';
import CustomerReviews from './CustomerReviews';
import Hero from './Hero';
import IconsTextsList from './IconsTextsList';
import InfiniteImagesSlider from './InfiniteImagesSlider';
import SpacedUnstructuredTextImages from './SpacedUnstructuredTextImages';
import TextImagesSlider from './TextImagesSlider';
import UnstructuredTextImages from './UnstructuredTextImages';

export {
	ButtonLinks,
	CustomerReviews,
	Hero,
	IconsTextsList,
	InfiniteImagesSlider,
	SpacedUnstructuredTextImages,
	TextImagesSlider,
	UnstructuredTextImages,
};

export const components = {
	button_links: ButtonLinks,
	customer_reviews: CustomerReviews,
	hero: Hero,
	icons_texts_list: IconsTextsList,
	infinite_images_slider: InfiniteImagesSlider,
	spaced_unstructured_text_images: SpacedUnstructuredTextImages,
	text_images_slider: TextImagesSlider,
	unstructured_text_images: UnstructuredTextImages,
};
